// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WebsiteStatus string

const (
	WebsiteStatusUP       WebsiteStatus = "UP"
	WebsiteStatusDOWN     WebsiteStatus = "DOWN"
	WebsiteStatusTIMEOUT  WebsiteStatus = "TIMEOUT"
	WebsiteStatusDNSERROR WebsiteStatus = "DNS_ERROR"
	WebsiteStatusSSLERROR WebsiteStatus = "SSL_ERROR"
)

func (e *WebsiteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebsiteStatus(s)
	case string:
		*e = WebsiteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebsiteStatus: %T", src)
	}
	return nil
}

type NullWebsiteStatus struct {
	WebsiteStatus WebsiteStatus `json:"website_status"`
	Valid         bool          `json:"valid"` // Valid is true if WebsiteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebsiteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebsiteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebsiteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebsiteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebsiteStatus), nil
}

type Region struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	CountryCode string    `json:"country_code"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Name         pgtype.Text `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

type Website struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Url       string           `json:"url"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type WebsiteTick struct {
	ID             uuid.UUID          `json:"id"`
	WebsiteID      uuid.UUID          `json:"website_id"`
	RegionID       uuid.UUID          `json:"region_id"`
	Status         WebsiteStatus      `json:"status"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
