// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regions.sql

package store

import (
	"context"
)

const listRegions = `-- name: ListRegions :many
SELECT
    id,
    name,
    country_code
FROM regions
ORDER BY name ASC
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(&i.ID, &i.Name, &i.CountryCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
