// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: website_ticks.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getLast24HoursTicksForWebsite = `-- name: GetLast24HoursTicksForWebsite :many
SELECT
    website_id,
    region_id,
    status,
    response_time_ms,
    created_at
FROM website_ticks
WHERE website_id = $1
  AND created_at >= NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC
`

func (q *Queries) GetLast24HoursTicksForWebsite(ctx context.Context, websiteID uuid.UUID) ([]WebsiteTick, error) {
	rows, err := q.db.Query(ctx, getLast24HoursTicksForWebsite, websiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebsiteTick
	for rows.Next() {
		var i WebsiteTick
		if err := rows.Scan(
			&i.WebsiteID,
			&i.RegionID,
			&i.Status,
			&i.ResponseTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatest100TicksForWebsite = `-- name: GetLatest100TicksForWebsite :many
SELECT
    website_id,
    region_id,
    status,
    response_time_ms,
    created_at
FROM website_ticks
WHERE website_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) GetLatest100TicksForWebsite(ctx context.Context, websiteID uuid.UUID) ([]WebsiteTick, error) {
	rows, err := q.db.Query(ctx, getLatest100TicksForWebsite, websiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebsiteTick
	for rows.Next() {
		var i WebsiteTick
		if err := rows.Scan(
			&i.WebsiteID,
			&i.RegionID,
			&i.Status,
			&i.ResponseTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestTickForWebsite = `-- name: GetLatestTickForWebsite :one
SELECT
    website_id,
    region_id,
    status,
    response_time_ms,
    created_at
FROM website_ticks
WHERE website_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTickForWebsite(ctx context.Context, websiteID uuid.UUID) (WebsiteTick, error) {
	row := q.db.QueryRow(ctx, getLatestTickForWebsite, websiteID)
	var i WebsiteTick
	err := row.Scan(
		&i.WebsiteID,
		&i.RegionID,
		&i.Status,
		&i.ResponseTimeMs,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebsiteTick = `-- name: InsertWebsiteTick :exec
INSERT INTO website_ticks (
    website_id,
    region_id,
    status,
    response_time_ms,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
)
`

type InsertWebsiteTickParams struct {
	WebsiteID      uuid.UUID     `json:"website_id"`
	RegionID       uuid.UUID     `json:"region_id"`
	Status         WebsiteStatus `json:"status"`
	ResponseTimeMs int32         `json:"response_time_ms"`
}

func (q *Queries) InsertWebsiteTick(ctx context.Context, arg InsertWebsiteTickParams) error {
	_, err := q.db.Exec(ctx, insertWebsiteTick,
		arg.WebsiteID,
		arg.RegionID,
		arg.Status,
		arg.ResponseTimeMs,
	)
	return err
}
