// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: websites.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO websites (
    name,
    url,
    user_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    name,
    url,
    user_id,
    created_at,
    updated_at
`

type CreateWebsiteParams struct {
	Name   string    `json:"name"`
	Url    string    `json:"url"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error) {
	row := q.db.QueryRow(ctx, createWebsite, arg.Name, arg.Url, arg.UserID)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebsite = `-- name: DeleteWebsite :execrows
DELETE FROM websites
WHERE id = $1
  AND user_id = $2
`

type DeleteWebsiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebsite(ctx context.Context, arg DeleteWebsiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebsite, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listWebsitesByUser = `-- name: ListWebsitesByUser :many
SELECT
    id,
    name,
    url,
    user_id,
    created_at,
    updated_at
FROM websites
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebsitesByUser(ctx context.Context, userID uuid.UUID) ([]Website, error) {
	rows, err := q.db.Query(ctx, listWebsitesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Website
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
